name: Validate TOML with TYML

on:
  push:
    branches:
      - '**'          # すべてのブランチの push（= 各コミット）で実行
  pull_request:       # PR 上の各コミットでも実行（任意）
  workflow_dispatch:  # 手動実行（任意）

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # 同じブランチで新しい push が来たら古い実行をキャンセル

jobs:
  tyml-validate:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with: { cache-on-failure: true }
      - name: Install tyml CLI
        run: |
          if ! command -v tyml >/dev/null 2>&1; then
            cargo install tyml_core
          fi
          tyml --version || true
      - name: Validate servers.toml with tyml
        run: |
          test -f servers.toml || { echo "servers.toml not found"; exit 1; }
          tyml servers.toml

